config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :boats, only: [:index]
  end

  resources :boats do
    resources :reviews
    resources :bookings, only: [:create, :new]
  end

  resources :bookings, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  patch "confirm_booking/:id", to: "bookings#confirm", as: :confirm
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :user

  mount_uploader :photo, PhotoUploader

  validates :name, presence:true, uniqueness: true
  validates :description, presence:true
  validates :price_per_hour, presence:true
  validates :hours, presence:true
  validates :capacity, presence:true
  # validates :category, presence:true
  validates_inclusion_of :has_license, in: [true, false]

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_address?

  def rating
    (reviews.average(:rating) || 0).round
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat

  enum status: { pending: 0, cancelled: 1, confirmed: 2, archived: 3 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :boat
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boats, dependent: :destroy
  has_many :bookings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :photo, PhotoUploader

  def bookings_for_boats
    #find all the boats and the bookings belonging to the boats
    # boats.map do | boat|
    #   boat.bookings
    # end.flatten
    Booking.all.joins(:boat).where('boats.user_id = ?', id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :photo_cache])
  end

  protect_from_forgery
  before_action :authenticate_user!

  include Pundit

  # # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController

  def index
    if user_id = params[:user_id]
      @user = User.find(user_id)
      @boats = policy_scope(Boat).where(user: @user)
    else
      @boats = policy_scope(Boat)
    end

  end

  def show

    @boat = Boat.find(params[:id])

    authorize @boat

    @boat.geocode

    @markers = [
      {
        lat: @boat.latitude,
        lng: @boat.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }]
  end

  def new
    @boat = Boat.new
    authorize @boat
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user = current_user
    authorize @boat

    if @boat.save
      redirect_to boats_path
    else
      render :new
    end
  end

  def edit
    @boat = Boat.find(params[:id])
    authorize @boat
  end

  def update
    @boat = Boat.find(params[:id])
    authorize @boat
    @boat.update(boat_params)
    redirect_to boat_path(@boat)
  end

  def destroy
    @boat = Boat.find(params[:id])
    authorize @boat
    @boat.destroy
    redirect_to boats_path
  end


  def boat_params
    params.require(:boat).permit(:name, :description, :location, :price_per_hour,
      :hours, :capacity, :has_license, :photo, :latitude, :longitude)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    if user_id = params[:user_id]
      @user = User.find(user_id)
      @bookings = policy_scope(Booking).where(user: @user)
    else
      @bookings = policy_scope(Booking)
    end
  end

  def new
    @boat = Boat.find(params[:boat_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @boat = Boat.find(params[:boat_id])

    if @boat.user == current_user
      raise "Not allowed to rent your own boat"
    end

    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.user = current_user
    @booking.boat = @boat

    if @booking.save
      @booking.status = "pending"  #update status
      @booking.save
      redirect_to boat_path(@boat)
    else
      render :new
    end
  end

  def confirm
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update! status: "confirmed"
    redirect_to user_path(current_user)
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update!(booking_params)
    @user = @booking.user
    redirect_to bookings_path
  end

  private
  def booking_params
     params.require(:booking).permit(:start_time, :end_time, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @boats = Boat.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    if boat_id = params[:boat_id]
      @boat = Boat.find(boat_id)
      @reviews = @boat.reviews
    else
      @reviews = Review.all
    end
  end

  def new
    @boat = Boat.find(params[:boat_id])
    @review = Review.new
    authorize @review
  end

  def create
    @user = current_user
    @boat = Boat.find(params[:boat_id])
    @review = Review.new(review_params)
    authorize @review
    @review.user = @user
    @review.boat = @boat
    if @review.save
      redirect_to boat_path(@boat)
    else
      render :new
    end
  end

  def destroy
    @boat = Boat.find(params[:boat_id])
    @review = Review.find(params[:id])
    authorize @review
    @review.destroy
    redirect_to boat_path(@boat)
  end

    def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    #this displays the bookings for the user
    @user = User.find(params[:id])

    if params[:show]
      @bookings = @user.bookings.where(status: params[:show])
    else
      @bookings = @user.bookings
    end
    authorize @user

    if params[:show]
      @bookings_for_boats = @user.bookings_for_boats.where(status: params[:show])
    else
      @bookings_for_boats = @user.bookings_for_boats
    end
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    authorize @user
    if @user.save
      redirect_to user_path(@user)
    else
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/edit.html.erb
<h2>Change boat details</h2>

<div class="devise-input-form">

  <%= simple_form_for(@boat) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :location %>
    <%= f.input :price_per_hour  %>
    <%= f.input :hours  %>
    <%= f.input :capacity  %>
    <%= f.input :category  %>
    <%= f.input :has_license, as: :radio_buttons%>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit %>
  <% end %>

  <%= link_to "Back to list",  user_boats_path(@boat.user)%>
</div>

app/views/boats/index.html.erb
<h2>List of Boats</h2>

<div class="container">
 <div class="row">
   <% @boats.each do |b| %>
   <div class="col-xs-12 col-md-4">
      <%= link_to boat_path(b) do %>
     <%= render "shared/boatcard", boat: b %>
     <% end %>
   </div>
   <% end %>
 </div>
</div>

app/views/boats/new.html.erb
<h1>Add a boat</h1>

<div class="devise-input-form">

<%= simple_form_for(@boat) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :price_per_hour  %>
  <%= f.input :hours  %>
  <%= f.input :capacity  %>
  <%= f.input :category  %>
  <%= f.input :has_license, as: :radio_buttons%>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>

<% end %>

<%= link_to "Back to list",  boats_path, class: "style: margin-botton: 5px"%>

</div>

app/views/boats/show.html.erb
<div class= "wrapper-light">
  <div class="grid-container">

    <!-- Boat Details -->

    <div class="grid-item1 grid-item">
      <div class="name-image" >
      <h2 class="boat-name" ><%= @boat.name %></h2>
      <%= cl_image_tag(@boat.photo.present? ? @boat.photo : "boat_placeholder", height: 300, width: 400, crop: :fill ) %>
      <p style="margin-top: 20px"><%= cl_image_tag(@boat.user.photo.present? ? @boat.user.photo : "avatar_placeholder", height: 100, width: 100, class: "img-circle") %></p>
      <p>Owner: <span class="hd"><%= @boat.user.first_name.present? ? @boat.user.first_name : @boat.user.email %></span></p>
      </div>
      <div>
        <ul>
          <li>
            <p><strong>Rating: </strong> <%= @boat.rating %> </p>
            <p><strong>Category: </strong><%= @boat.category %></p>
            <p><strong>Location: </strong><%= @boat.location %></p>
            <p><strong>Price per hour: </strong>  <%= @boat.price_per_hour %>€</p>
            <p><strong>Rental hours: </strong> <%= @boat.hours %></p>
            <p><strong>Capacity:</strong> <%= @boat.capacity %></p>
            <p><strong>License needed?</strong>
              <%if @boat.has_license %>
              <%= "Yes" %>
                <% else %>
              <%= "No" %>
                <% end  %>
            </p>
          </li>
        </ul>
      <% if policy(@boat).edit? %>
      <p class="boat-p"><%= link_to "Edit Boat", edit_boat_path(@boat), class: "boat-btn"%></p>
      <% end %>
      <% if policy(@boat).destroy? %>
      <p class="boat-p"><%= link_to "Delete", boat_path(@boat),
      method: :delete,
      data: { confirm: "Are you sure?" }, class: "boat-btn"%></p>
      <p class="boat-p"><%= link_to "Back to list", boats_path, class: "boat-btn"%></p>
      <% end %>
      </div>
    </div>

    <!-- Boat Description -->

    <div class="grid-item2 grid-item">
      <p><strong>Description</strong>: <%= @boat.description %></p>
    </div>

     <!-- Booking Details -->

    <div class="grid-item4 grid-item">
      <h2 class="book-details show-title">Bookings</h2>
      <ul>
        <% @boat.bookings.each do |booking| %>
        <li>
          <p> Status: <span class="status"> <%= booking.status %> </span> </p>
          <p> Start: <%= booking.start_time.strftime("%Y-%m-%d (%H:%M)") %></p>
          <p> End: <%= booking.end_time.strftime("%Y-%m-%d (%H:%M)") %> </p>
          <p> *** </p>
        </li>
        <% end %>
      </ul>
      <div class="btn-details">
        <% if @boat.user != current_user %>
        <p class="boat-p"><%= link_to "Book this boat", new_boat_booking_path(@boat), class: "boat-btn"%></p>
        <% end %>
      </div>
    </div>

    <!-- Boat Reviews -->

    <div class="grid-item5 grid-item">
      <h2 class="show-title">Reviews</h2>
      <ul>
        <% @boat.reviews.each do |review| %>
        <li>
          <strong><%= review.title %> </strong>
          <% if policy(review).destroy? %>
          <%= link_to "", boat_review_path(@boat, review),
          method: :delete,
          data: { confirm: "Are you sure?" }, class: "far fa-trash-alt" %>
          <% end %>
          <br>
          <p><em>"<%= review.content %>"</em></p>
          <p> Rating: <%= review.rating %> </p>
          <p> *** </p>
        </li>
        <% end %>
      </ul>

      <p class="boat-p"><%= link_to "Add a review", new_boat_review_path(@boat), class: "boat-btn"%></p>
    </div>


  </div>
</div>
<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>">
</div>

app/views/bookings/edit.html.erb
<h2>Edit this booking</h2>
<div class="devise-input-form">
<h4> Boat: <strong> <%= @booking.boat.name %> <strong> </h4>
<h4>Owner: <strong> <%= @booking.user.first_name %>
  <%= @booking.user.last_name %> </strong></h4>
 <%= simple_form_for([@boat, @booking]) do |f| %>
   <%= f.input :start_time%>
   <%= f.input :end_time %>
   <%= f.input :status, collection: Booking.statuses.keys %>
   <%= f.submit "Update booking"%>
 <% end %>
</div>

app/views/bookings/index.html.erb
<div class="wrapper-light">
<h2 class="booking-h2">List of Bookings</h2>
<!--   <div class="application-controller"> -->
    <div class="container">

    <div class="container booking-container">

      <% @bookings.each do |b| %>

      <div class="row booking-body">
        <div class="col col-xs-12 booking-col">
          <div class="long-card">

            <div class="book-id">
              <p class="hd"> Owner </p>
              <p> <%= b.user.first_name[0] %>. <%= b.user.last_name %> </p>
            </div>
            <div class= "book-name">
              <p class="hd"> Boat Name</p>
              <p><%= b.boat.name %> </p>
            </div>
            <div class= "book-start">
              <p class="hd"> Start time</p>
              <p><%= b.start_time.strftime("%Y-%m-%d (%H:%M)") %> </p>
            </div>
            <div class= "book-end">
              <p class="hd"> End time</p>
              <p><%= b.end_time.strftime("%Y-%m-%d (%H:%M)") %> </p>
            </div>
            <div class= "book-price">
              <p class="hd"> Price (€)</p>
              <p><%= b.boat.price_per_hour %> </p>
            </div>
            <div class= "book-status">
              <p class="hd"> Status </p>
              <p><%= b.status %> </p>
            </div>
            <div>
              <%= link_to "Update", edit_booking_path(b), class:"book-btn"%>
            </div>
          </div>
        </div>
      </div>

       <%end %>

      </div>
    </div>
<!--   </div> -->
</div>

app/views/bookings/new.html.erb
<h1>Reserve your boat: <%= @boat.name %></h1>
<div class="devise-input-form">
   <%= simple_form_for([@boat, @booking]) do |f| %>
     <%= f.input :start_time%>
     <%= f.input :end_time %>
     <%= f.submit %>
   <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AnchorZone</title>
    <link href = “images/boat-logo” rel=“icon” type=“image/ico”>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="application-container">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/banner" %>

<div class="home-container">
<h2>Top deals</h2>
<div class="container">
 <div class="row">
   <% @boats.first(3).each do |b| %>
     <div class="col-xs-12 col-md-4">
       <%= link_to boat_path(b) do %>
       <%= render "shared/boatcard", boat: b %>
       <% end %>
     </div>
   <% end %>
 </div>
</div>
<div>
  <h2>Mission</h2>
  <div class="home-content" >
    <p>We created this platform with the idea of bringing together people that are passionate about water and who are looking for alternative ways of finding the best boat rides of their lives. Whether you want to get away from the crowd, spend quality time with your family, or just have a crazy birthday party on a boat, with our growing network, we believe you will all find something truly unique. While searching for a boat on our site, you not only support the owner, but you also contribute to sustainability, to community and if you book a boat without an engine, the environment as well. And for those, who prefer the other way, the good news is that our luxury boat category is continuously expanding...

      <p> HAPPY CRUISING! </p>
    </p>
  </div>
</div>
<!-- <div class="bottom-padding"></div> -->
</div>

app/views/reviews/new.html.erb
<h2>Add a review</h2>

<div class="devise-input-form">
  <%= simple_form_for([@boat, @review]) do |f| %>
    <%= f.input :title%>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit %>
  <% end %>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path('banner_boat_final.png') %>);">
  <div class="banner-content">
    <h1 class="banner-title">AnchorZone</h1>
    <p>Find your best ride on water</p>
   <!--  <a class="btn btn-lg banner-btn show-btn" href="">Explore!</a> -->
    <%= link_to "Explore!", boats_path, class:"btn btn-lg banner-btn show-btn" %>
  </div>
</div>

app/views/shared/_boatcard.html.erb
<div class= "card-link">
  <div class="card"
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path(boat.photo.present? ? boat.photo : "boat_placeholder") %>')">
    <div class="card-category">
      <%= boat.category %>
      <p><%= boat.name %></p>
    </div>
    <div class="card-description">
      <% boat.rating.times do%>
        <i class="fas fa-star star-orange"></i>
      <% end %>
      <% (5 - boat.rating).times do %>
        <i class="fas fa-star star-grey"></i>
      <% end %>
    </div>
    <div class="card-cost">
      <strong><p>€<%= boat.price_per_hour %></p></strong>
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path(boat.photo.present? ? boat.photo : "boat_placeholder") %>')">
  <div class="card-category"><%= boat.name %></div>
  <div class="card-description">
    <h2><%= boat.name %></h2>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="far fa-copyright"></i> SubMasters 2018
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "boat_logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "My profile", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "All bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "All boats", boats_path, class: "navbar-wagon-item navbar-wagon-link" %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag(current_user.photo.present? ? current_user.photo : "avatar_placeholder", height: 300, width: 300, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"  )%>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
   <!--          <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li> -->
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <!-- <%= link_to "Sign up" %> - Needs a Sign up link  -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
    <!--     <li><a href="#">Contact</a></li>
        <li><a href="#">About</a></li> -->
        <li><%= link_to "My profile", user_path(:id)%></li>
        <li> <%= link_to "All boats", boats_path %> </li>
      </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
  <h2>Edit your name</h2>
<div class="devise-input-form">

<%= simple_form_for(@user) do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit %>
<% end %>

<p><%= link_to "Delete this user", user_path(@user), method: :delete, data: { confirm: "Are you sure?"}, class: "devise-btn"%></p>
</div>

app/views/users/show.html.erb
 <h2 class="h2-user">Hello <%= @user.first_name%>!</h2>
  <div class="main-container user-bin">
    <div id="profile-bin">
      <%= cl_image_tag(current_user.photo.present? ? current_user.photo : "avatar_placeholder", height: 300, width: 300, crop: :fill) %>
      <p>First name: <%= @user.first_name%></p>
      <p>Last name: <%= @user.last_name%></p>
      <p>Email: <%= @user.email%></p>
      <% @user.boats.each do |boat| %>
      <p>Boat: <strong> <%= link_to  boat.name, boat_path(boat) %> </strong> </p>

      <% end %>
      <p><%= link_to "Back to boats",  boats_path, class: "booking-btn"%> </p>
      <p><%= link_to "Add a boat",  new_boat_path, class: "booking-btn"%> </p>
      <p><%= link_to "Edit profile",  edit_user_path(@user), class: "booking-btn"%> </p>
    </div>

    <div class="container booking-container">
      <div class="row">
        <div class="col-xs-12 booking-title">
          <h3 class="show-h2">Your Bookings</h3>
        </div>
      </div>
      <div class="row booking-header">
        <div class="col col-xs-4">
          <%= link_to "Pending", user_path(@user, show:"pending"), class: "status-btn" %>
        </div>
        <div class="col col-xs-4">
            <%= link_to "Confirmed", user_path(@user, show:"confirmed"), class: "status-btn" %>
        </div>
        <div class="col col-xs-4">
            <%= link_to "Cancelled", user_path(@user, show:"cancelled"), class: "status-btn" %>
        </div>
      </div>

      <% @bookings.each do |b| %>

      <div class="row booking-body">
        <div class="col col-xs-12 booking-col">
          <div class="long-card">

            <div class="book-id">
              <p class="hd">Name</p>
              <p> <%= b.user.first_name[0]%>. <%= b.user.last_name %> </p>
            </div>
            <div class= "book-name">
              <p class="hd"> Boat Name</p>
              <p><%= b.boat.name %> </p>
            </div>
            <div class= "book-start">
              <p class="hd"> Start time</p>
              <p><%= b.start_time.strftime("%Y-%m-%d (%H:%M)") %> </p>
            </div>
            <div class= "book-end">
              <p class="hd"> End time</p>
              <p><%= b.end_time.strftime("%Y-%m-%d (%H:%M)") %> </p>
            </div>
            <div class= "book-price">
              <p class="hd"> Price (€)</p>
              <p><%= b.boat.price_per_hour %> </p>
            </div>
            <div>
              <%= link_to "Update", edit_booking_path(b), class:"book-btn"%>
            </div>
          </div>
        </div>
      </div>

       <%end %>

       <div class="row">
        <div class="col-xs-12 booking-title">
          <h3 class="show-h2">Your <strong>Boat</strong> Bookings</h3>
        </div>
      </div>
      <div class="row booking-header">
        <div class="col col-xs-4">
          <%= link_to "Pending", user_path(@user, show:"pending"), class: "status-btn" %>
        </div>
        <div class="col col-xs-4">
            <%= link_to "Confirmed", user_path(@user, show:"confirmed"), class: "status-btn" %>
        </div>
        <div class="col col-xs-4">
            <%= link_to "Cancelled", user_path(@user, show:"cancelled"), class: "status-btn" %>
        </div>
      </div>

            <% @bookings_for_boats.each do |b| %>

      <div class="row booking-body">
        <div class="col col-xs-12 booking-col">
          <div class="long-card">

            <div class="book-id">
              <p class="hd">Name</p>
              <p> <%= b.user.first_name[0]%>. <%= b.user.last_name %> </p>
            </div>
            <div class= "book-name">
              <p class="hd"> Boat Name</p>
              <p><%= b.boat.name %> </p>
            </div>
            <div class= "book-start">
              <p class="hd"> Start time</p>
              <p><%= b.start_time.strftime("%Y-%m-%d (%H:%M)") %> </p>
            </div>
            <div class= "book-end">
              <p class="hd"> End time</p>
              <p><%= b.end_time.strftime("%Y-%m-%d (%H:%M)") %> </p>
            </div>
            <div class= "book-price">
              <p class="hd"> Price (€)</p>
              <p><%= b.boat.price_per_hour %> </p>
            </div>
            <div>
              <% if b.status != "confirmed" %>
                <%= link_to "Confirm", confirm_path(b), method: :patch, class:"book-btn"%>
              <%end %>
            </div>
          </div>
        </div>
      </div>

       <%end %>

    </div>

  </div>